# Generated by Django 5.0 on 2023-12-26 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="supervisor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_department",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="task",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to="service.task",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="worker",
            field=models.ManyToManyField(
                related_name="working_departments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
