# Generated by Django 5.0 on 2023-12-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_supervisor_department_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='task',
        ),
    ]
