# Generated by Django 5.0 on 2023-12-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_department_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='worker',
            new_name='workers',
        ),
    ]
