# Generated by Django 5.0 on 2023-12-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_worker_department_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Image',
            new_name='image',
        ),
    ]
