# Generated by Django 5.0 on 2023-12-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_department_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='workers',
            new_name='worker',
        ),
    ]
