# Generated by Django 5.0 on 2023-12-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_task_supervisor_alter_task_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
    ]
