# Generated by Django 5.0 on 2024-01-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_task_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supervisor_status',
            field=models.CharField(choices=[('uncompleted', 'Uncompleted'), ('completed', 'Completed')], default='uncompleted', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_status',
            field=models.CharField(choices=[('none', 'None'), ('in_progress', 'In Progress')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
