# Generated by Django 4.2.7 on 2024-01-01 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content',
            new_name='reply_content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='image',
            new_name='reply_image',
        ),
    ]
