# Generated by Django 5.0 on 2024-01-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_task_supervisor_status_task_worker_status_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
