# Generated by Django 5.0 on 2024-01-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content',
            new_name='reply_content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='image',
            new_name='reply_image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='supervisor_status',
            field=models.CharField(choices=[('uncompleted', 'Uncompleted'), ('completed', 'Completed')], default='uncompleted', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_status',
            field=models.CharField(choices=[('none', 'None'), ('in_progress', 'In Progress')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='service.comment'),
        ),
    ]
