# Generated by Django 4.2.7 on 2024-01-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_rename_content_reply_reply_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
