# Generated by Django 5.0 on 2023-12-28 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='img/logo.png', upload_to='img/')),
                ('supervisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_department', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ManyToManyField(related_name='working_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
